#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

docker build -f ../circleci.dockerfile -t esup-circleci ../linux/amd64 &&
  {
    docker tag esup-circleci hdpe/esup-circleci:latest || exit 1

    if [ -n "${TRAVIS_TAG}" ]; then
      docker tag esup-circleci "hdpe/esup-circleci:${TRAVIS_TAG}" || exit 1
    fi
  } &&
  echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin &&
  {
    docker push hdpe/circleci || exit 1

    if [ -n "${TRAVIS_TAG}" ]; then
      docker push "hdpe/esup-circleci:${TRAVIS_TAG}" || exit 1
    fi
  }
